gca_mvp/gca_mvp/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import handler404, handler500
from supporting_business import views as sp_views

urlpatterns = [
                  url('admin/', include(admin.site.urls)),

                  url(r'^', include('supporting_business.urls')),

                  # url(r'^login/$', login, name='login', kwargs={'template_name': 'accounts/login.html'}),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler404 = sp_views.error_404
handler500 = sp_views.error_500

gca_mvp/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import handler404, handler500
from supporting_business import views as sp_views

urlpatterns = [
                  url('admin/', include(admin.site.urls)),

                  url(r'^', include('supporting_business.urls')),

                  # url(r'^login/$', login, name='login', kwargs={'template_name': 'accounts/login.html'}),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#
# handler404 = sp_views.error_404
# handler500 = sp_views.error_500
# handler500 = sp_views.error_500

gca_mvp/supporting_business/forms.py
from django import forms
from django.forms import ModelForm, TextInput, Textarea
from .models import *
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User
from django.forms.widgets import ClearableFileInput

import os
# missing imports
from django.utils.safestring import mark_safe
from os import path
from django import forms


class FormatString(str):
    def format(self, *args, **kwargs):
        arguments = list(args)
        arguments[1] = path.basename(arguments[1])
        return super(FormatString, self).format(*arguments, **kwargs)


class ClearableFileInput(forms.ClearableFileInput):
    url_markup_template = FormatString('<a href="{0}">{1}</a>')


class LoginForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password']

    username = forms.EmailField(label="아이디", label_suffix="",
                                widget=forms.TextInput(attrs={'placeholder': 'example@gconnect.co.kr'}),
                                error_messages={'invalid': _(
                                    "이메일 형식과 맞지 않습니다.")}
                                )

    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': '비밀번호를 입력하세요'}), label="비밀번호",
                               label_suffix="",
                               )

    def clean_username(self):
        """
        Validate that the username is alphanumeric and is not already
        in use.

        """
        existing = User.objects.filter(username__iexact=self.cleaned_data['username'])
        if existing.exists():
            raise forms.ValidationError(_("같은 아이디의 유저가 존재합니다. 다른 이메일을 사용하여주세요."))
        else:
            return self.cleaned_data['username']


class ManagerForm(forms.ModelForm):
    class Meta:
        model = AdditionalUserInfo
        fields = ["name", "position", "tel", "web"]
        labels = {
            "name": _("이름"),
            "position": _("담당(직급,소속)"),
            "tel": _("전화번호"),
            "web": _("추가정보 안내 홈페이지 URL")
        }
        widgets = {
            "name": TextInput(),
            "position": TextInput(),
            "tel": TextInput(),
            "web": TextInput(),
        }


class NewStartupUp(forms.Form):
    uid = forms.CharField(widget=forms.HiddenInput())
    name = forms.CharField(label="기업명", label_suffix="")
    established_date = forms.DateField(label="설립일", label_suffix="", widget=forms.TextInput(
        attrs={'class': 'addy_title', "placeholder": "YYYY-MM-DD 형태로 입력"}))
    category = forms.CharField(label="사업분야", label_suffix="", required=False)
    address_0_title = forms.CharField(label="", required=False, widget=forms.TextInput(
        attrs={'class': 'addy_title', "placeholder": "소재지명 ex)본사", }))
    address_0 = forms.CharField(label="", required=False, widget=forms.TextInput(attrs={'class': 'addy',
                                                                                        "placeholder": "주소를 입력하세요", }))
    address_0_detail = forms.CharField(label="", required=False,
                                       widget=forms.TextInput(
                                           attrs={'placeholder': '세부 주소를 입력하세요.', 'class': 'addy_detail'}))

    address_1_title = forms.CharField(label="", required=False, widget=forms.TextInput(
        attrs={'class': 'addy_title', "placeholder": "소재지명 ex)본사", }))
    address_1 = forms.CharField(label="", required=False, widget=forms.TextInput(attrs={'class': 'addy',
                                                                                        "placeholder": "주소를 입력하세요", }))
    address_1_detail = forms.CharField(label="", required=False,
                                       widget=forms.TextInput(
                                           attrs={'placeholder': '세부 주소를 입력하세요.', 'class': 'addy_detail'}))
    address_2_title = forms.CharField(label="", required=False, widget=forms.TextInput(
        attrs={'class': 'addy_title', "placeholder": "소재지명 ex)본사", }))
    address_2 = forms.CharField(label="", required=False, widget=forms.TextInput(attrs={'class': 'addy',
                                                                                        "placeholder": "주소를 입력하세요", }))
    address_2_detail = forms.CharField(label="", required=False,
                                       widget=forms.TextInput(
                                           attrs={'placeholder': '세부 주소를 입력하세요.', 'class': 'addy_detail'}))

    address = forms.CharField(label="소재지", widget=forms.TextInput(attrs={'placeholder': '주소를 입력하세요.'}),
                              label_suffix="", required=False)

    email = forms.CharField(label="대표 메일", widget=forms.TextInput(attrs={'placeholder': 'company@mail.com'}),
                            label_suffix="", required=False)
    website = forms.CharField(label="홈페이지", widget=forms.TextInput(attrs={'placeholder': 'www.companywebsite.com'}),
                              label_suffix="", required=False)
    employee_number = forms.CharField(label="구성원수", label_suffix="", required=False)


class NewStartupBot(forms.Form):
    keyword = forms.CharField(required=False, widget=forms.Textarea(attrs={'placeholder': '#키워드로 입력하세요.'}))
    desc = forms.CharField(required=False, widget=forms.Textarea(attrs={'placeholder': ''}))
    service_products = forms.CharField(required=False, widget=forms.Textarea(attrs={'placeholder': ''}))
    short_desc = forms.CharField(required=False, widget=forms.Textarea(attrs={'placeholder': ''}))

    revenue_before_year_0 = forms.CharField(required=False, )
    revenue_before_year_1 = forms.CharField(required=False, )
    revenue_before_year_2 = forms.CharField(required=False, )
    revenue_before_0 = forms.CharField(required=False, )
    revenue_before_1 = forms.CharField(required=False, )
    revenue_before_2 = forms.CharField(required=False, )

    export_before_year_0 = forms.CharField(required=False, )
    export_before_year_1 = forms.CharField(required=False, )
    export_before_year_2 = forms.CharField(required=False, )
    export_before_0 = forms.CharField(required=False, )
    export_before_1 = forms.CharField(required=False, )
    export_before_2 = forms.CharField(required=False, )

    fund_before_0 = forms.CharField(required=False, )
    fund_before_1 = forms.CharField(required=False, )
    fund_before_2 = forms.CharField(required=False, )
    fund_before_3 = forms.CharField(required=False, )
    fund_before_4 = forms.CharField(required=False, )
    fund_before_5 = forms.CharField(required=False, )
    fund_before_6 = forms.CharField(required=False, )
    fund_before_7 = forms.CharField(required=False, )
    fund_before_8 = forms.CharField(required=False, )
    fund_before_9 = forms.CharField(required=False, )

    fund_before_year_0 = forms.CharField(required=False, )
    fund_before_year_1 = forms.CharField(required=False, )
    fund_before_year_2 = forms.CharField(required=False, )
    fund_before_year_3 = forms.CharField(required=False, )
    fund_before_year_4 = forms.CharField(required=False, )
    fund_before_year_5 = forms.CharField(required=False, )
    fund_before_year_6 = forms.CharField(required=False, )
    fund_before_year_7 = forms.CharField(required=False, )
    fund_before_year_8 = forms.CharField(required=False, )
    fund_before_year_9 = forms.CharField(required=False, )

    fund_before_agent_0 = forms.CharField(required=False, )
    fund_before_agent_1 = forms.CharField(required=False, )
    fund_before_agent_2 = forms.CharField(required=False, )
    fund_before_agent_3 = forms.CharField(required=False, )
    fund_before_agent_4 = forms.CharField(required=False, )
    fund_before_agent_5 = forms.CharField(required=False, )
    fund_before_agent_6 = forms.CharField(required=False, )
    fund_before_agent_7 = forms.CharField(required=False, )
    fund_before_agent_8 = forms.CharField(required=False, )
    fund_before_agent_9 = forms.CharField(required=False, )




class MyPageUp(forms.Form):
    # pw =forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': ''}), label="PW",
    #                            label_suffix="",
    #                            )
    uid = forms.CharField(widget=forms.HiddenInput())
    name = forms.CharField(label="이름", label_suffix="" ,  required=False)


class MyPageBot(forms.Form):
    tel = forms.CharField(label="핸드폰 번호", label_suffix="", help_text="핸드폰 번호로 유용한 알람이 갑니다.", required=False)
    additional_email = forms.CharField(label="추가 email", label_suffix="",
                                       required=False)
    agreement = forms.BooleanField(label="수신 동의", label_suffix="", required=False)
    # position = forms.CharField(label="내 직책", label_suffix="",  required=False, widget=forms.TextInput(attrs={'placeholder': 'CEO'}))


class SupportBusinessForm(forms.Form):
    title = forms.CharField(label="지원 사업명", widget=forms.TextInput(attrs={'placeholder': '지원 사업명을 입력하세요'}))
    from_date = forms.DateField(widget=forms.TextInput(attrs={'placeholder': '공고 시작 날짜'}))
    end_date = forms.DateField(widget=forms.TextInput(attrs={'placeholder': '공고 마감 날짜'}))
    abstract = forms.CharField(widget=forms.Textarea)
    target = forms.CharField(widget=forms.Textarea)
    detail = forms.CharField(widget=forms.Textarea)
    apply_method = forms.CharField(widget=forms.Textarea(attrs={"placeholder": "예) 온라인 폼, 사업자 등록증 첨부"}))
    etc = forms.CharField(
        widget=forms.Textarea(attrs={"placeholder": "※ 자세한 사항은 소상공인시장진흥공단(www.semas.or.kr) → 알림마당 → 공지사항 참조(☞바로가기)"}))


class SupportForm(forms.ModelForm):
    class Meta:
        model = SupportBusiness
        fields = '__all__'

        labels = {
            "title": _("지원사업명")
        }
        widgets = {
            "title": TextInput(attrs={'placeholder': '지원 사업명을 입력하세요'}),
            "from_date": TextInput(attrs={'placeholder': '공고 시작 날짜'}),
            "end_date": TextInput(attrs={'placeholder': '공고 마감 날짜'}),
            "abstract": Textarea,
            "target": Textarea,

gca_mvp/templates/pc/manage_support_list.html
{% extends "pc/common/base_d.html" %}
{% load static %}

{% block css %}
    <link rel="stylesheet/less" href="{% static "css/new_support.css" %}"/>
    <style>
    </style>
{% endblock %}


{% block content %}

    <div id="left_col">
        <ul>
            <li>
                <a href="#">통계보기</a>
            </li>
            <li>
                <a href="{% url "new_support" %}">지원사업 등록페이지</a>
            </li>
            <li>
                <a href="{% url "manage_support" %}">지원사업 관리 페이지</a>
            </li>
        </ul>
    </div>
    <div id="body_content">
        {% for q in qs %}
            <div class="sp_seg">
                <div class="status">{{ q.is_past_due }}</div>
                <div class="create_date">등록일 {{ q.createdate }}</div>
                <div class="sp_category">공간지원 > 오피스 지원</div>
                <div class="sp_title">{{ q.title }}</div>
                <div class="view">조회수 {{ q.hit }}</div>
                <div class="applier">현재 지원자 {{ q.apply_num }}</div>
                <div class="due">모집기간 {{ q.from_date }}~{{ q.end_date }}</div>
                <div class="btn_group">
                    <button class="sp_btn" onclick="location.href= '{{ q.get_absolute_url_manage }}' ">상세 보기</button>
                    <button class="sp_btn">통계로 보기</button>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

gca_mvp/templates/pc/matching_temporary.html
{% extends "pc/common/base_d.html" %}
{% load static %}
{% load custom_filter %}
{% block css %}
    <link href="{% static "css/index.css" %}" rel="stylesheet/less">
{% endblock %}
{% block content %}
    <script>
        $(document).ready(function () {
            $("#u_login_pass").css("height", $(window).height())

        })
    </script>

    {% if user.is_authenticated %}
        <style>
            #u_login_pass {
                background-color: #fff;
                background-color: rgba(255, 225, 48, 0.7);
            }

            #cp {
                color: #2b2b2b;
                font-size: 40px;
                font-weight: 100;
            }

            #cp > span {
                font-weight: 300 !important;
                color: #2b2b2b;
                font-size: 40px;
            }

            #go_reg {
                width: 150px;
                height: 29px;
                border-radius: 17px;
                background-color: #1b66f4;
                text-align: center;
                line-height: 29px;
                color: #fff;
                margin-top: 29px;
                display: inline-block;
                margin-right: 15px;
                cursor: pointer;
            }

            #no {
                font-size: 15px;
                color: #2b2b2b;
            }
        </style>


        <div class="row" id="u_login_pass">
            <div class="container">
                <div id="cp" style="margin-top: 283px;">
                    G-CONNECT에서 <span>회원가입/기업등록</span>을 통해<br>
                    당신의 기업에게 맞는 지원사업을 찾아보세요.
                </div>
                <div id="go_reg" onclick="location.href='{% url "company_profile" %}'">
                    지금 기업등록하기
                </div>
                <a href="{% url "search" %}"><span id="no">그냥 전체 지원사업 볼래요</span></a>
            </div>
        </div>
    {% else %}

        <style>
            #u_login_pass {
                background-color: #fff;
                background-color: rgba(27, 102, 244, 0.7);
            }

            #cp {
                color: #fff;
                font-size: 40px;
                font-weight: 100;
            }

            #cp > span {
                font-weight: 300 !important;
                color: #fff;
                font-size: 40px;
            }

            #go_reg {
                width: 150px;
                height: 29px;
                border-radius: 17px;
                background-color: #ffffff;
                text-align: center;
                line-height: 29px;
                color: #1b66f4;
                margin-top: 29px;
                display: inline-block;
                margin-right: 15px;
                cursor: pointer;
            }

            #no {
                font-size: 15px;
                color: #fff;
            }
        </style>


        <div class="row" id="u_login_pass">
            <div class="container">
                <div id="cp" style="margin-top: 283px;">
                    G-CONNECT에서 <span>회원가입/기업등록</span>을 통해<br>
                    당신의 기업에게 맞는 지원사업을 찾아보세요.
                </div>
                <div id="go_reg" onclick="location.href='{% url "signup" %}'">
                    지금 회원가입하기
                </div>
                <a href="{% url "search" %}"><span id="no">그냥 전체 지원사업 볼래요</span></a>
            </div>
        </div>

    {% endif %}
{% endblock %}

gca_mvp/templates/pc/mypage.html
{% extends "pc/common/base_d.html" %}
{% load static %}
{% load custom_filter %}
{% block css %}
    <link href="{% static "css/mypage.css" %}" rel="stylesheet/less">
    <link rel="stylesheet/less" href="{% static "css/app_mypage_menu.css" %}">

{% endblock %}

{% block content %}
    <script>
        $(document).ready(function () {
            var cert = $("#cert_email").detach();
            $("#id_email").parent().append(cert)
        })
    </script>
    <div class="container">
        <div id="brd_cumb">
            <a href="{% url "index" %}">홈</a> &nbsp;&gt;&nbsp; <a id="final" href="#">내프로필</a>
        </div>
        {% include "pc/common/mypage_menu.html" %}
        <div id="detail_top">
            <div id="main">
                    {% user_avatar user %}
            </div>

            <div id="name_ttl">{%if user.additionaluserinfo.name  != "" %}
                        {{ user.additionaluserinfo.name }}
                        {% else %}이름을 입력 해주세요.{% endif %}</div>
          {%  user_social user as test %}
           {%  if not test  %}
            <div id="email_ttl">

                {{ user.username }}
            </div>
        {% endif %}
            <form method="post" action="">
                {% csrf_token %}
                <div id="profile_up">
                    <li><label for="id_name">연동된 SNS</label>{% user_social user %}</li>
                {%  user_social user as test %}
                    {%  if not test  %}
                    <li><label for="id_name">ID</label>
                        {{ user.username }}
                    </li>
                    <li><label for="id_name">PW</label> ******</li>
                    {% endif %}
                    <li><label for="id_name">이름</label>{%if user.additionaluserinfo.name  != "" %}
                        {{ user.additionaluserinfo.name }}
                        {% else %}이름을 입력 해주세요.{% endif %}

                    </li>
                </div>
                <div id="profile_bot">
                    <li><label for="id_name">핸드폰번호</label> {{ user.additionaluserinfo.tel }}</li>
                    <li><label for="id_name">추가 email</label> {{ user.additionaluserinfo.additional_email }}</li>
                    <li><label for="id_name">수신동의</label>
                        {% if user.additionaluserinfo.agreement == True %}
                        <img src="{% static "img/icon_done.png" %}"
                             style="width: 16px;margin-top: -3px;margin-right:10px;"> 네
                        {% else %}
                        <img src="{% static "img/icon_done.png" %}"
                             style="width: 16px;margin-top: -3px;margin-right:10px;"> 아니오
                        {% endif %}
                    </li>
                 {% comment %}   <li><label for="id_name">소속기업</label>{{ user.additionaluserinfo.startup }}</li>
                    <li><label for="id_name">역할</label> {{ user.additionaluserinfo.position }}</li>{% endcomment %}
                </div>
                <div onclick="location.href='../../mypage/my_profile/edit'" id="modify"
                     style="margin-left: 353px;cursor: pointer">수정 하기
                </div>
            </form>
        </div>

    </div>
{% endblock %}

gca_mvp/templates/pc/new_support_business.html
{% extends "pc/common/base_d.html" %}
{% load static %}

{% block css %}
    <link rel="stylesheet/less" href="{% static "css/new_support.css" %}"/>
    <style>
    </style>
{% endblock %}


{% block content %}
    <script
            src="https://code.jquery.com/ui/1.12.0/jquery-ui.js"
            integrity="sha256-0YPKAwZP7Mp3ALMRVB2i8GXeEndvCq3eSl/WsAl1Ryk="
            crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static "css/jquery_ui.css" %}"/>
    <script>
        var selected_filter = []
        $(document).ready(function () {
            $(".tag").on("click", function () {
                if ($(this).hasClass("on")) {
                    selected_filter.slice(selected_filter.indexOf($(this).attr("data-id")), 1)
                    $(this).removeClass("on")
                }
                else {
                    selected_filter.push($(this).attr("data-id"))
                    $(this).addClass("on")
                }
                console.log(selected_filter)
                $("#filter").attr("value", selected_filter.join(","))
            })
        })
        $(function () {
            $("#id_from_date, #id_end_date").datepicker({
                dateFormat: 'yy-mm-dd',
                prevText: '이전 달',
                nextText: '다음 달',
                monthNames: ['1월', '2월', '3월', '4월', '5월', '6월', '7월', '8월', '9월', '10월', '11월', '12월'],
                monthNamesShort: ['1월', '2월', '3월', '4월', '5월', '6월', '7월', '8월', '9월', '10월', '11월', '12월'],
                dayNames: ['일', '월', '화', '수', '목', '금', '토'],
                dayNamesShort: ['일', '월', '화', '수', '목', '금', '토'],
                dayNamesMin: ['일', '월', '화', '수', '목', '금', '토'],
                showMonthAfterYear: true,
                changeMonth: true,
                changeYear: true,
                yearSuffix: '년'
            });
        });
    </script>
    <div id="left_col">
        <ul>
            <li>
                <a href="#">통계보기</a>
            </li>
            <li>
                <a href="{% url "new_support" %}">지원사업 등록페이지</a>
            </li>
            <li>
                <a href="{% url "manage_support" %}">지원사업 관리 페이지</a>
            </li>
        </ul>
    </div>
    <div id="body_content">
        <form method="post">
            {% csrf_token %}
            <input type="hidden" id="filter" name="filter">
            <div class="input_form">
                <div class="input_label">지원 사업 명</div>
                {{ form.title }}
                다른 공고 글 불러오기
            </div>
            <div class="input_form">
                <div class="input_label">모집기간</div>
                {{ form.from_date }}~{{ form.end_date }}
            </div>
            <div class="input_form">
                <div class="input_label">대상 기업(필터)</div>
                <table style="clear:both;">
                    <tr>
                        <th>
                            기본장르
                        </th>
                        <td>
                            {% for filter in filter_0 %}
                                <span class="tag" data-id="{{ filter.id }}">{{ filter.name }}</span>
                            {% endfor %}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            영역
                        </th>
                        <td>
                            <span class="cat_label">창작</span>
                            {% for filter in filter_1 %}
                                <span class="tag" data-id="{{ filter.id }}">{{ filter.name }}</span>
                            {% endfor %}<br>
                            <span class="cat_label">IT 관련</span>
                            {% for filter in filter_2 %}
                                <span class="tag" data-id="{{ filter.id }}">{{ filter.name }}</span>
                            {% endfor %}<br>
                            <span class="cat_label">창업</span>
                            {% for filter in filter_3 %}
                                <span class="tag" data-id="{{ filter.id }}">{{ filter.name }}</span>
                            {% endfor %}<br>
                            <span class="cat_label">제조/융합</span>
                            {% for filter in filter_4 %}
                                <span class="tag" data-id="{{ filter.id }}">{{ filter.name }}</span>
                            {% endfor %}<br>
                            <span class="cat_label">신규산업</span>
                            {% for filter in filter_5 %}
                                <span class="tag" data-id="{{ filter.id }}">{{ filter.name }}</span>
                            {% endfor %}<br>
                            <span class="cat_label">기타</span>
                            {% for filter in filter_6 %}
                                <span class="tag" data-id="{{ filter.id }}">{{ filter.name }}</span>
                            {% endfor %}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            조건
                        </th>
                        <td>
                            <span class="cat_label">업력</span>
                            {% for filter in filter_7 %}
                                <span class="tag" data-id="{{ filter.id }}">{{ filter.name }}</span>
                            {% endfor %}<br>
                            <span class="cat_label">구성원</span>
                            {% for filter in filter_8 %}
                                <span class="tag" data-id="{{ filter.id }}">{{ filter.name }}</span>
                            {% endfor %}<br>
                            <span class="cat_label">소재지</span>
                            {% for filter in filter_9 %}
                                <span class="tag" data-id="{{ filter.id }}">{{ filter.name }}</span>
                            {% endfor %}<br>
                            <span class="cat_label">기업형태</span>
                            {% for filter in filter_10 %}
                                <span class="tag" data-id="{{ filter.id }}">{{ filter.name }}</span>
                            {% endfor %}<br>
                            <span class="cat_label">기업단계</span>
                            {% for filter in filter_11 %}
                                <span class="tag" data-id="{{ filter.id }}">{{ filter.name }}</span>
                            {% endfor %}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            지원 형태
                        </th>
                        <td>
                            <span class="cat_label">자금</span>
                            {% for filter in filter_12 %}
                                <span class="tag" data-id="{{ filter.id }}">{{ filter.name }}</span>
                            {% endfor %}<br>
                            <span class="cat_label">투자연계</span>
                            {% for filter in filter_13 %}
                                <span class="tag" data-id="{{ filter.id }}">{{ filter.name }}</span>
                            {% endfor %}<br>
                            <span class="cat_label">교육</span>
                            {% for filter in filter_14 %}
                                <span class="tag" data-id="{{ filter.id }}">{{ filter.name }}</span>
                            {% endfor %}<br>
                            <span class="cat_label">판로</span>
                            {% for filter in filter_15 %}
                                <span class="tag" data-id="{{ filter.id }}">{{ filter.name }}</span>
                            {% endfor %}<br>
                            <span class="cat_label">네트워킹</span>
                            {% for filter in filter_16 %}
                                <span class="tag" data-id="{{ filter.id }}">{{ filter.name }}</span>
                            {% endfor %}<br>
                            <span class="cat_label">기타지원</span>
                            {% for filter in filter_17 %}
                                <span class="tag" data-id="{{ filter.id }}">{{ filter.name }}</span>
                            {% endfor %}<br>
                            <span class="cat_label">공간지원</span>
                            {% for filter in filter_18 %}
                                <span class="tag" data-id="{{ filter.id }}">{{ filter.name }}</span>
                            {% endfor %}<br>
                        </td>
                    </tr>
                </table>
            </div>
            <div class="input_form">
                <div class="input_label">모집 방식 선택</div>
            </div>
            <div class="input_form">
                <div class="input_label">사업 개요</div>
                {{ form.abstract }}
            </div>
            <div class="input_form">
                <div class="input_label">
                    지원 분야 및 대상
                </div>
                {{ form.target }}
            </div>
            <div class="input_form">
                <div class="input_label">
                    내용
                </div>
                {{ form.detail }}
            </div>
            <div class="input_form">
                <div class="input_label">신청방법 및 서류</div>
                {{ form.apply_method }}
            </div>
            <div class="input_form">
                <div class="input_label">기타 사항</div>
                {{ form.etc }}
            </div>
            <div class="input_form">
                <div class="input_label">
                    주관 기관 담당부서 및 담당자
                </div>
            </div>
            <div id="btn_group">
                <button id="reserve">예약게시</button>
                <button type="submit" id="register">공고글 게시</button>
            </div>
        </form>
    </div>
{% endblock %}

gca_mvp/templates/pc/p404.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>G-connect</title>
<script>
    setTimeout(function () {
        {% if target == "m" %}
        location.href="{% url "dashboard" %}"
        {% else %}
        location.href="{% url "index" %}"
        {% endif %}
    }, 5000)
</script>
</head>

<body>
페이지를 찾을수 없습니다. 5초후에 메인 페이지로 이동합니다.
</body>
</html>

gca_mvp/templates/pc/p500.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>G-connect</title>
<script>
    setTimeout(function () {
        {% if target == "m" %}
        location.href="{% url "dashboard" %}"
        {% else %}
        location.href="{% url "index" %}"
        {% endif %}
    }, 5000)
</script>
</head>

<body>
에러가 발생했습니다. 5초후에 메인 페이지로 이동합니다.
</body>
</html>